spring.application.name=movie-platform
spring.datasource.url=jdbc:mysql://localhost:3306/movie_db
spring.datasource.username=root
spring.datasource.password=Chikklu@30062015

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true